apiVersion: v1
kind: Service
metadata:
  name: data-portal-service
  labels:
    app.kubernetes.io/name: data-portal
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: data-portal
  ports:
  - protocol: TCP
    port: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-portal-deployment
  labels:
    app.kubernetes.io/name: data-portal
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-portal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: data-portal
    spec:
      containers:
      - name: data-portal
        image: jh1104/data-portal:latest
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 500m
        env:
        - name: DATA_PORTAL_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: data-portal-auth-key
