apiVersion: v1
kind: Service
metadata:
  name: jarvis-service
  labels:
    app.kubernetes.io/name: jarvis
    app.kubernetes.io/component: bot
spec:
  type: ClusterIP
  selector:
    app: jarvis
  ports:
  - protocol: TCP
    port: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvis-deployment
  labels:
    app.kubernetes.io/name: jarvis
    app.kubernetes.io/component: bot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jarvis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: jarvis
    spec:
      containers:
      - name: jarvis
        image: jh1104/jarvis:latest
        resources:
          requests:
            memory: 128Mi
            cpu: 200m
          limits:
            memory: 512Mi
            cpu: 1000m
        env:
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: slack-app-token
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: slack-bot-token
